-------------------------------------------------------------------------------
//USER_INFO TABLE 

-- 테이블 삭제
DROP TABLE USER_INFO;

-- 테이블 생성
CREATE TABLE USER_INFO(
    USER_NO NUMBER(6) NOT NULL,
    NAME VARCHAR2(80) NOT NULL,
    NICKNAME VARCHAR2(100) NOT NULL,
    ID VARCHAR2(50)NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,    
    PHONE VARCHAR2(15)NOT NULL,    
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    AUTHORITY VARCHAR2(30) DEFAULT 'user' NOT NULL,
    USER_LEAVE VARCHAR2(15) DEFAULT 'N'   
);


-- 제약사항 수정
ALTER TABLE USER_INFO
ADD CONSTRAINT USER_NO_PK PRIMARY KEY(USER_NO);

ALTER TABLE USER_INFO
ADD CONSTRAINT NICKNAME_UK UNIQUE(NICKNAME);

ALTER TABLE USER_INFO
ADD CONSTRAINT ID_UK UNIQUE(ID);

ALTER TABLE USER_INFO
ADD CONSTRAINT PHONE_UK UNIQUE(PHONE);


-- 시퀀스 삭제
DROP SEQUENCE USER_NO_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE USER_NO_SEQ
INCREMENT BY 1
START WITH 1;



-- 데이터 삽입

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE, AUTHORITY)
VALUES (USER_NO_SEQ.NEXTVAL, 'EVEMT', 'EVENT', 'EVEMT', 'EVENT',  'EVENT', 'admin');

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE, AUTHORITY)
VALUES (USER_NO_SEQ.NEXTVAL, 'qudcjf123', '1234', '조병철', 'JJJBC',  '01098765432', 'admin');

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE, AUTHORITY)
VALUES (USER_NO_SEQ.NEXTVAL, 'alswo456', '1125', '김민재', 'MINJJAe',  '01052439563', 'admin');

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE, AUTHORITY)
VALUES (USER_NO_SEQ.NEXTVAL, '1234', '1234', '국하현', 'QUEEN1234',  '01085112345', 'admin');

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE, AUTHORITY)
VALUES (USER_NO_SEQ.NEXTVAL, 'youk', '777', '김유경', 'youk',  '01065987123', 'admin');

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, 'bkbk', '1595', '김보근', 'fightking',  '01077777123');

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, 'smoker', '1595', '김진우', 'smoker',  '01065411123');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '이서연', '더연', 'theyeon', '1234', '010-7788-8877');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '이채영', '챙그랑', 'rang', '1234', '010-8877-7788');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '이나경', '나꼬', 'na', '1234', '010-5050-0505');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '백지헌', '지헌', 'jiji', '1234', '010-0202-4612');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '안유진', '안댕댕', 'anan', '1234', '010-0303-4612');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '장원영', '워뇨', 'rarari', '1234', '010-0202-9801');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '레이', '레이', 'ray', '1234', '010-3410-4697');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '이서연', '더연2', 'theyeon2', '1234', '010-7788-3134');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '이채영', '챙그랑2', 'rang2', '1234', '010-8877-4567');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '이나경', '나꼬2', 'na2', '1234', '010-5050-9898');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '백지헌', '지헌2', 'jiji32', '1234', '010-0812-3212');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '안유진', '안댕댕2', 'anan32', '1234', '010-3103-7777');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '장원영', '워뇨34', 'rarar12i', '1234', '010-1937-9801');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '레이', '레이45', 'ra12y', '1234', '010-7814-0042');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '안진유', '댕댕안', 'ananan', '1234', '010-0461-4612');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '장원영', '워뇨2', 'rarariri', '1234', '010-0221-9801');

INSERT INTO USER_INFO
(USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE)
VALUES (USER_NO_SEQ.NEXTVAL, '레이', '레이투', 'rayray', '1234', '010-3412-4647');


-- 데이터 확인
SELECT USER_NO, NAME, NICKNAME, ID, PASSWORD, PHONE, CREATED_DATE, UPDATE_DATE, AUTHORITY, USER_LEAVE
FROM USER_INFO;

-- 데이터 확인(날짜 데이터)
SELECT USER_NO, ID, TO_CHAR(CREATED_DATE, 'YYYY"년"MM"월"DD"일" HH24:MI:SS')
FROM USER_INFO;

-- 커밋
COMMIT;
-------------------------------------------------------------------------------
    
