-------------------------------------------------------------------------------
//AREA TABLE 

-- 테이블 삭제
DROP TABLE AREA;

-- 테이블 생성
CREATE TABLE AREA(
    AREA_NO NUMBER(2) NOT NULL,
    AREA_NAME VARCHAR2(20) NOT NULL  
);

-- 제약사항 수정
ALTER TABLE AREA
ADD CONSTRAINT AREA_NO_PK PRIMARY KEY(AREA_NO);

ALTER TABLE AREA
ADD CONSTRAINT AREA_NAME_UK UNIQUE KEY(AREA_NAME);

-- 시퀀스 삭제
DROP SEQUENCE AREA_NO_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE AREA_NO_SEQ
INCREMENT BY 1
START WITH 1;

-- 데이터 삽입
INSERT INTO AREA
(AREA_NO, AREA_NAME)
VALUES (AREA_NO_SEQ.NEXTVAL, '경기도');

INSERT INTO AREA
(AREA_NO, AREA_NAME)
VALUES (AREA_NO_SEQ.NEXTVAL, '강원도');

INSERT INTO AREA
(AREA_NO, AREA_NAME)
VALUES (AREA_NO_SEQ.NEXTVAL, '충청도');

INSERT INTO AREA
(AREA_NO, AREA_NAME)
VALUES (AREA_NO_SEQ.NEXTVAL, '전라도');

INSERT INTO AREA
(AREA_NO, AREA_NAME)
VALUES (AREA_NO_SEQ.NEXTVAL, '경상도');

INSERT INTO AREA
(AREA_NO, AREA_NAME)
VALUES (AREA_NO_SEQ.NEXTVAL, '제주도');

-- 데이터 확인
SELECT AREA_NO, AREA_NAME
FROM AREA;

DESC AREA;


-- 커밋
COMMIT;
-------------------------------------------------------------------------------