
//게시판정보
DROP TABLE BOARD_INFO;

-- 게시판 상단
CREATE TABLE BOARD_INFO(
	BOARD_INFO_NO NUMBER(6) NOT NULL, -- 기본키설정 
	BOARD_INFO_NAME VARCHAR2(500) NOT NULL 
);

-- 제약사항 수정
ALTER TABLE BOARD_INFO
ADD CONSTRAINT  BOARD_INFO_NO_PK PRIMARY KEY(BOARD_INFO_NO);

-- 데이터 삽입

insert into board_info(BOARD_INFO_NO,BOARD_INFO_NAME)
values(1, '공지게시판');
insert into board_info(BOARD_INFO_NO,BOARD_INFO_NAME)
values(2, '자유게시판');
insert into board_info(BOARD_INFO_NO,BOARD_INFO_NAME)
values(3, '리뷰게시판');
insert into board_info(BOARD_INFO_NO,BOARD_INFO_NAME)
values(4, '고객센터');


-- 데이터 확인
SELECT * FROM BOARD_INFO;

-- 커밋
COMMIT;
//게시판테이블 첨부파일은 언젠간 구현예정

DROP TABLE BOARD_CONTENT;

--게시판 상세
CREATE TABLE BOARD_CONTENT(
	CONTENT_NO NUMBER(6) NOT NULL ,
	CONTENT_SUBJECT VARCHAR2(500) NOT NULL,
	CONTENT_TEXT LONG NOT NULL,
	CONTENT_FILE VARCHAR2(500),
    CONTENT_BOARD_INFO_NO NUMBER(6),
    CONTENT_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONTENT_UPDATE_DATE DATE NOT NULL,
    USER_NO NUMBER(6) NOT NULL    
);

-- 제약사항 수정
ALTER TABLE BOARD_CONTENT
ADD CONSTRAINT  CONTENT_NO_PK PRIMARY KEY(CONTENT_NO);

ALTER TABLE BOARD_CONTENT
ADD CONSTRAINT BOARD_CONTENT_USER_NO_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO (USER_NO);

ALTER TABLE BOARD_CONTENT
ADD CONSTRAINT BOARD_CONTENT_BOARD_INFO_NO_FK FOREIGN KEY(CONTENT_BOARD_INFO_NO) REFERENCES BOARD_INFO (BOARD_INFO_NO);

-- 시퀀스 삭제
DROP SEQUENCE CONTENT_NO_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE CONTENT_NO_SEQ
INCREMENT BY 1
START WITH 1;

-- 데이터 삽입
INSERT INTO BOARD_CONTENT 
(CONTENT_NO, CONTENT_SUBJECT, CONTENT_TEXT, CONTENT_FILE, CONTENT_BOARD_INFO_NO, CONTENT_UPDATE_DATE, USER_NO) 
VALUES (CONTENT_NO_SEQ.NEXTVAL, 'TEST_BOARD', 'TEXT_COMMENT', 'intro_to_sql.pdf', 1, SYSDATE, 1);

INSERT INTO BOARD_CONTENT 
(CONTENT_NO, CONTENT_SUBJECT, CONTENT_TEXT, CONTENT_FILE, CONTENT_BOARD_INFO_NO, CONTENT_UPDATE_DATE, USER_NO) 
VALUES (CONTENT_NO_SEQ.NEXTVAL, '리뷰예시', '리뷰게시판판성공햇냐', 'default', 3, SYSDATE, 4);

INSERT INTO BOARD_CONTENT 
(CONTENT_NO, CONTENT_SUBJECT, CONTENT_TEXT, CONTENT_FILE, CONTENT_BOARD_INFO_NO, CONTENT_UPDATE_DATE, USER_NO) 
VALUES (CONTENT_NO_SEQ.NEXTVAL, '삭제용', '리뷰게시판판성공햇냐', 'default', 3, SYSDATE, 4);


-- 데이터 확인
SELECT CONTENT_NO, CONTENT_SUBJECT, CONTENT_TEXT, CONTENT_FILE, CONTENT_BOARD_INFO_NO, CONTENT_CRE_DATE, CONTENT_UPDATE_DATE, USER_NO
FROM BOARD_CONTENT;

-- 커밋
COMMIT;


