-------------------------------------------------------------------------------
//BOARD_CONTENT_COMMENT TABLE 

-- 테이블 삭제
DROP TABLE BOARD_CONTENT_COMMENT;

-- 테이블 생성
CREATE TABLE BOARD_CONTENT_COMMENT(
    COMMENT_NO NUMBER(6) NOT NULL,
    CONTENT_NO NUMBER(6) NOT NULL,
    CONTENT_COMMENT VARCHAR2(200) NOT NULL,
    USER_NO NUMBER(6) NOT NULL,
    COMMENT_CRE_DATE DATE DEFAULT SYSDATE, 
    COMMENT_UPDATE_DATE DATE DEFAULT SYSDATE
);

-- 제약사항 수정
ALTER TABLE BOARD_CONTENT_COMMENT
ADD CONSTRAINT COMMENT_NO_PK PRIMARY KEY(COMMENT_NO);

ALTER TABLE BOARD_CONTENT_COMMENT
ADD CONSTRAINT CONTENT_NO_FK FOREIGN KEY(CONTENT_NO) REFERENCES BOARD_CONTENT (CONTENT_NO);

ALTER TABLE BOARD_CONTENT_COMMENT
ADD CONSTRAINT B_C_C_USER_NO_FK FOREIGN KEY(USER_NO) REFERENCES BOARD_CONTENT (USER_NO);


-- 시퀀스 삭제
DROP SEQUENCE COMMENT_NO_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE COMMENT_NO_SEQ
INCREMENT BY 1
START WITH 1;

-- 데이터 삽입
INSERT INTO BOARD_CONTENT_COMMENT
(COMMENT_NO, CONTENT_NO, CONTENT_COMMENT, USER_NO)
VALUES (COMMENT_NO_SEQ.NEXTVAL, 1, '가나다라', 2);

INSERT INTO BOARD_CONTENT_COMMENT
(COMMENT_NO, CONTENT_NO, CONTENT_COMMENT, USER_NO)
VALUES (COMMENT_NO_SEQ.NEXTVAL, 1, '마바사', 2);



-- 테이블 구조 확인
DESC BOARD_CONTENT_COMMENT;

-- 데이터 확인
SELECT COMMENT_NO, CONTENT_NO, CONTENT_COMMENT, COMMENT_CRE_DATE, COMMENT_UPDATE_DATE
FROM BOARD_CONTENT_COMMENT;


-- 커밋
COMMIT;
-------------------------------------------------------------------------------