-------------------------------------------------------------------------------
//BOARD_CONTENT_IMG TABLE 

-- 테이블 삭제
DROP TABLE BOARD_CONTENT_IMG;

-- 테이블 생성
CREATE TABLE BOARD_CONTENT_IMG(
    BOARD_IMG_NO NUMBER(6) NOT NULL,
    CONTENT_NO NUMBER(6) NOT NULL,
    CONTENT_IMG_PATH VARCHAR2(1000) DEFAULT ''  
);

-- 제약사항 수정
ALTER TABLE BOARD_CONTENT_IMG
ADD CONSTRAINT BOARD_IMG_NO_PK PRIMARY KEY(BOARD_IMG_NO);

ALTER TABLE BOARD_CONTENT_IMG
ADD CONSTRAINT IMG_CONTENT_NO_FK FOREIGN KEY(CONTENT_NO) REFERENCES BOARD_CONTENT (CONTENT_NO);

-- 시퀀스 삭제
DROP SEQUENCE BOARD_IMG_NO;

-- 시퀀스 생성
CREATE SEQUENCE BOARD_IMG_NO
INCREMENT BY 1
START WITH 1;


-- 데이터 확인
SELECT BOARD_IMG_NO, CONTENT_NO, CONTENT_IMG_PATH
FROM BOARD_CONTENT_IMG;

DESC BOARD_CONTENT_IMG;


-- 커밋
COMMIT;
-------------------------------------------------------------------------------