-------------------------------------------------------------------------------
//PLACE_COMMENT TABLE 

-- 테이블 삭제
DROP TABLE PLACE_COMMENT;

-- 테이블 생성
CREATE TABLE PLACE_COMMENT(
    PLACE_COMMENT_NO NUMBER(6) NOT NULL,
    PLACE_NO NUMBER(6) NOT NULL,
    USER_NO NUMBER(6) NOT NULL,
    COMMENT_CONTENTS VARCHAR2(200) NOT NULL,
    COMMENT_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    COMMENT_UPDATE_DATE DATE NOT NULL
);

-- 제약사항 수정
ALTER TABLE PLACE_COMMENT
ADD CONSTRAINT PLACE_COMMENT_NO PRIMARY KEY(PLACE_COMMENT_NO);

ALTER TABLE PLACE_COMMENT
ADD CONSTRAINT P_COMMENT_PLACE_NO_FK FOREIGN KEY(PLACE_NO) REFERENCES PLACE (PLACE_NO);

ALTER TABLE PLACE_COMMENT
ADD CONSTRAINT USER_INFO_USER_NO_FK FOREIGN KEY(USER_NO) REFERENCES USER_INFO (USER_NO);


-- 시퀀스 삭제
DROP SEQUENCE PLACE_COMMENT_NO_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE PLACE_COMMENT_NO_SEQ
INCREMENT BY 1
START WITH 1;

-- 데이터 삽입
INSERT INTO PLACE_COMMENT
(PLACE_COMMENT_NO, PLACE_NO, USER_NO, COMMENT_CONTENTS, COMMENT_UPDATE_DATE)
VALUES (PLACE_COMMENT_NO_SEQ.NEXTVAL, 1, 2, SYSDATE);

INSERT INTO PLACE_COMMENT
(PLACE_COMMENT_NO, PLACE_NO, USER_NO, COMMENT_CONTENTS, COMMENT_UPDATE_DATE)
VALUES (PLACE_COMMENT_NO_SEQ.NEXTVAL, 2, 2, SYSDATE);



-- 테이블 구조 확인
DESC PLACE_COMMENT;

-- 데이터 확인
SELECT PLACE_COMMENT_NO, PLACE_NO, USER_NO, COMMENT_CONTENTS, COMMENT_CRE_DATE, COMMENT_UPDATE_DATE
FROM PLACE_COMMENT;


-- 커밋
COMMIT;
-------------------------------------------------------------------------------